[
    {
        "type": "root",
        "tabs": [
            {
                "id": "tab_1",
                "label": "Nube Sinte",
                "tabs": [
                    {
                        "id": "tab_2",
                        "label": "Recuperar",
                        "widgets": [
                            {
                                "type": "knob",
                                "top": 10,
                                "left": 10,
                                "id": "HFC",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 200,
                                "height": 170,
                                "color": "auto",
                                "compact": false,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "address": "/mir/hfc/mean",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "pips": false,
                                "doubleTap": false
                            },
                            {
                                "type": "knob",
                                "top": 10,
                                "left": 220,
                                "id": "Spectral Complexity",
                                "linkId": "ss",
                                "label": "auto",
                                "unit": "",
                                "width": 190,
                                "height": 170,
                                "color": "auto",
                                "compact": false,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "address": "/mir/spectral_complexity/mean",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "pips": false,
                                "doubleTap": false
                            },
                            {
                                "type": "switch",
                                "top": 180,
                                "left": 50,
                                "linkId": "",
                                "label": "auto",
                                "width": 130,
                                "height": 50,
                                "horizontal": true,
                                "color": "red",
                                "css": "",
                                "values": {
                                    "ON": 1,
                                    "OFF": -1
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/HFC/mean/on",
                                "preArgs": [],
                                "target": [],
                                "id": "HFC (mean)"
                            },
                            {
                                "type": "fader",
                                "top": 410,
                                "left": 0,
                                "id": "BPM",
                                "label": "auto",
                                "unit": "",
                                "width": 720,
                                "height": 70,
                                "alignRight": false,
                                "horizontal": true,
                                "compact": true,
                                "color": "auto",
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 50,
                                    "max": 200
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 0,
                                "meter": false,
                                "address": "/mir/bpm",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "touchAddress": "",
                                "meterAddress": "",
                                "pips": true,
                                "doubleTap": false
                            },
                            {
                                "type": "switch",
                                "top": 180,
                                "left": 250,
                                "label": "auto",
                                "width": 130,
                                "height": 50,
                                "horizontal": true,
                                "color": "red",
                                "css": "",
                                "values": {
                                    "ON": 1,
                                    "OFF": -1
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/spectral_complexity/mean/on",
                                "preArgs": [],
                                "target": [],
                                "id": "SC (mean)",
                                "linkId": ""
                            },
                            {
                                "type": "switch",
                                "top": 410,
                                "left": 730,
                                "label": "auto",
                                "width": 90,
                                "height": 70,
                                "horizontal": true,
                                "color": "red",
                                "css": "",
                                "values": {
                                    "on": 1,
                                    "off": 0
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/mir/bpm/enabled",
                                "preArgs": [],
                                "target": [],
                                "id": "bpm_state",
                                "linkId": ""
                            },
                            {
                                "type": "push",
                                "top": 10,
                                "left": 830,
                                "id": "Get new!",
                                "linkId": "",
                                "label": "auto",
                                "width": 140,
                                "height": 470,
                                "color": "auto",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "norelease": false,
                                "precision": 2,
                                "address": "/retrieve",
                                "preArgs": [],
                                "target": []
                            },
                            {
                                "type": "fader",
                                "top": 330,
                                "left": 0,
                                "id": "Duration (seg)",
                                "label": "auto",
                                "unit": "",
                                "width": 720,
                                "height": 70,
                                "alignRight": false,
                                "horizontal": true,
                                "compact": true,
                                "color": "auto",
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 15
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 1,
                                "meter": false,
                                "address": "/mir/duration",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "touchAddress": "",
                                "meterAddress": "",
                                "pips": true,
                                "doubleTap": false
                            },
                            {
                                "type": "switch",
                                "top": 330,
                                "left": 730,
                                "label": "auto",
                                "width": 90,
                                "height": 70,
                                "horizontal": true,
                                "color": "red",
                                "css": "",
                                "values": {
                                    "ON": 1,
                                    "OFF": 0
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/mir/duration/enabled",
                                "preArgs": [],
                                "target": [],
                                "id": "dur_state",
                                "linkId": ""
                            },
                            {
                                "type": "fader",
                                "top": 260,
                                "left": 0,
                                "id": "Spectral Centroid (mean)",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 720,
                                "height": 60,
                                "alignRight": false,
                                "horizontal": true,
                                "compact": true,
                                "color": "auto",
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 20,
                                    "max": 10000
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "meter": true,
                                "address": "/mir/spectral_centroid/mean",
                                "preArgs": [],
                                "target": [],
                                "precision": 0,
                                "touchAddress": "",
                                "meterAddress": "",
                                "pips": true,
                                "doubleTap": false
                            },
                            {
                                "type": "switch",
                                "top": 260,
                                "left": 730,
                                "label": "auto",
                                "width": 90,
                                "height": 60,
                                "horizontal": true,
                                "color": "red",
                                "css": "",
                                "values": {
                                    "ON": 1,
                                    "OFF": -1
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/mir/spectral_centroid/mean/enabled",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "id": "spec_cent"
                            },
                            {
                                "type": "knob",
                                "top": 10,
                                "left": 430,
                                "id": "Inharmonicity",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 170,
                                "height": 170,
                                "color": "auto",
                                "compact": false,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "address": "/mir/inharmonicity",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "pips": false,
                                "doubleTap": false
                            },
                            {
                                "type": "knob",
                                "top": 10,
                                "left": 620,
                                "id": "Pitch Centroid",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 180,
                                "height": 170,
                                "color": "auto",
                                "compact": false,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "address": "/mir/pitch_centroid/mean",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "pips": false,
                                "doubleTap": false
                            },
                            {
                                "type": "switch",
                                "top": 180,
                                "left": 450,
                                "label": "auto",
                                "width": 130,
                                "height": 50,
                                "horizontal": true,
                                "color": "red",
                                "css": "",
                                "values": {
                                    "ON": 1,
                                    "OFF": -1
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/inharmonicity/on",
                                "preArgs": [],
                                "target": [],
                                "id": "Inharm",
                                "linkId": ""
                            },
                            {
                                "type": "switch",
                                "top": 180,
                                "left": 640,
                                "width": 130,
                                "height": 50,
                                "horizontal": true,
                                "color": "red",
                                "css": "",
                                "values": {
                                    "ON": 1,
                                    "OFF": -1
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/pitch_centroid/mean/on",
                                "preArgs": [],
                                "target": [],
                                "id": "PC (mean)",
                                "linkId": "",
                                "label": "PC (mean)"
                            }
                        ],
                        "type": "tab",
                        "color": "auto",
                        "css": "",
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/tab_2",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "tabs": [],
                        "scroll": true
                    },
                    {
                        "id": "tab_3",
                        "label": "Síntesis",
                        "widgets": [
                            {
                                "type": "keyboard",
                                "id": "pitch",
                                "label": "auto",
                                "left": 0,
                                "top": 520,
                                "width": 820,
                                "height": 170,
                                "color": "auto",
                                "css": "",
                                "precision": 0,
                                "address": "/pitch",
                                "preArgs": [],
                                "target": [],
                                "keys": 24,
                                "start": 60,
                                "traversing": true,
                                "on": 1,
                                "off": 0,
                                "split": false
                            },
                            {
                                "type": "fader",
                                "top": 10,
                                "left": 860,
                                "id": "Volume",
                                "label": "auto",
                                "unit": "",
                                "width": "auto",
                                "height": "auto",
                                "alignRight": false,
                                "horizontal": false,
                                "compact": false,
                                "color": "auto",
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 10
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": true,
                                "precision": 2,
                                "meter": true,
                                "address": "/fx/volume",
                                "preArgs": [],
                                "target": [],
                                "linkId": "",
                                "touchAddress": "",
                                "meterAddress": "",
                                "pips": true,
                                "doubleTap": false
                            },
                            {
                                "type": "toggle",
                                "top": 0,
                                "left": 0,
                                "id": "Gate",
                                "linkId": "",
                                "label": "auto",
                                "width": 220,
                                "height": 70,
                                "color": "green",
                                "css": "",
                                "value": "",
                                "precision": 2,
                                "address": "/switch_5",
                                "preArgs": [],
                                "target": [],
                                "on": 1,
                                "off": 0
                            },
                            {
                                "type": "switch",
                                "top": 110,
                                "left": 0,
                                "id": "Freeze",
                                "label": "auto",
                                "width": 220,
                                "height": 110,
                                "horizontal": true,
                                "color": "auto",
                                "css": "",
                                "values": {
                                    "On": 1,
                                    "Off": -1
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/fx/freeze/on",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "switch",
                                "top": 250,
                                "left": 0,
                                "id": "Reverb",
                                "label": "auto",
                                "width": 220,
                                "height": 120,
                                "horizontal": true,
                                "color": "auto",
                                "css": "",
                                "values": {
                                    "On": 1,
                                    "Off": 2
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/switch_5",
                                "preArgs": [],
                                "target": [],
                                "linkId": ""
                            },
                            {
                                "type": "knob",
                                "top": 110,
                                "left": 250,
                                "id": "Position",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 130,
                                "height": 120,
                                "color": "auto",
                                "compact": false,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_6",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "pips": false,
                                "doubleTap": false
                            },
                            {
                                "type": "knob",
                                "top": 110,
                                "left": 400,
                                "id": "Width",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 130,
                                "height": 120,
                                "color": "auto",
                                "compact": false,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "address": "/knob_7",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "pips": false,
                                "doubleTap": false
                            },
                            {
                                "type": "knob",
                                "top": 250,
                                "left": 250,
                                "id": "Wet",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 130,
                                "height": 120,
                                "color": "auto",
                                "compact": false,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "address": "/fx/reverbwet",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "pips": false,
                                "doubleTap": false
                            },
                            {
                                "type": "knob",
                                "top": 250,
                                "left": 400,
                                "id": "Dry",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 130,
                                "height": 120,
                                "color": "auto",
                                "compact": false,
                                "angle": 270,
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": 0,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "address": "/fx/reverbdry",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "pips": false,
                                "doubleTap": false
                            },
                            {
                                "type": "fader",
                                "top": 390,
                                "left": 0,
                                "id": "PAN",
                                "linkId": "",
                                "label": "auto",
                                "unit": "",
                                "width": 820,
                                "height": 110,
                                "alignRight": false,
                                "horizontal": true,
                                "compact": false,
                                "color": "red",
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "range": {
                                    "min": -1,
                                    "max": 1
                                },
                                "origin": "auto",
                                "value": "",
                                "logScale": false,
                                "precision": 2,
                                "meter": false,
                                "address": "/fx/pan",
                                "preArgs": [],
                                "target": [],
                                "touchAddress": "",
                                "meterAddress": "",
                                "pips": true,
                                "doubleTap": false
                            },
                            {
                                "type": "xy",
                                "top": 10,
                                "left": 590,
                                "id": "spac",
                                "linkId": "",
                                "label": "auto",
                                "width": 250,
                                "height": 190,
                                "color": "auto",
                                "css": "",
                                "snap": false,
                                "spring": false,
                                "rangeX": {
                                    "min": 0,
                                    "max": 1
                                },
                                "rangeY": {
                                    "min": 0,
                                    "max": 1
                                },
                                "logScaleX": false,
                                "logScaleY": false,
                                "value": "",
                                "precision": 2,
                                "address": "/xy_1",
                                "preArgs": [],
                                "split": false,
                                "target": [],
                                "touchAddress": "",
                                "doubleTap": false
                            },
                            {
                                "type": "switch",
                                "top": 190,
                                "left": 560,
                                "id": "activate",
                                "linkId": "",
                                "label": "auto",
                                "width": 250,
                                "height": 50,
                                "horizontal": true,
                                "color": "auto",
                                "css": "",
                                "values": {
                                    "on": 1,
                                    "off": 2
                                },
                                "value": "",
                                "precision": 2,
                                "address": "/switch_1",
                                "preArgs": [],
                                "target": []
                            }
                        ],
                        "type": "tab",
                        "color": "auto",
                        "css": "",
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/tab_3",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "tabs": [],
                        "scroll": true
                    },
                    {
                        "id": "tab_4",
                        "label": "Text Search",
                        "widgets": [
                            {
                                "type": "toggle",
                                "top": 50,
                                "left": 60,
                                "id": "bajo",
                                "linkId": "",
                                "label": "auto",
                                "width": "auto",
                                "height": "auto",
                                "color": "auto",
                                "css": "",
                                "on": "bajo",
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/content",
                                "preArgs": [],
                                "target": []
                            },
                            {
                                "type": "toggle",
                                "top": 120,
                                "left": 210,
                                "id": "guitarra",
                                "linkId": "",
                                "label": "auto",
                                "width": "auto",
                                "height": "auto",
                                "color": "auto",
                                "css": "",
                                "on": "guitarra",
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/content",
                                "preArgs": [],
                                "target": []
                            },
                            {
                                "type": "toggle",
                                "top": 50,
                                "left": 420,
                                "id": "melodia",
                                "linkId": "",
                                "label": "auto",
                                "width": "auto",
                                "height": "auto",
                                "color": "auto",
                                "css": "",
                                "on": "melodia",
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/melodia",
                                "preArgs": [],
                                "target": []
                            }
                        ],
                        "type": "tab",
                        "color": "auto",
                        "css": "",
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/tab_4",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "tabs": [],
                        "scroll": true
                    },
                    {
                        "id": "tab_5",
                        "label": "Pattern",
                        "widgets": [
                            {
                                "type": "multitoggle",
                                "left": 10,
                                "top": 10,
                                "width": 960,
                                "height": 570,
                                "color": "green",
                                "css": "",
                                "matrix": [
                                    4,
                                    8
                                ],
                                "start": 0,
                                "traversing": true,
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 0,
                                "address": "/pattern",
                                "preArgs": [],
                                "split": false,
                                "target": [],
                                "id": "Pattern",
                                "label": "Pattern"
                            }
                        ],
                        "type": "tab",
                        "color": "auto",
                        "css": "",
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/tab_5",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "tabs": [],
                        "scroll": true
                    },
                    {
                        "id": "tab_6",
                        "label": "Samples",
                        "widgets": [
                            {
                                "type": "multitoggle",
                                "top": 0,
                                "left": 0,
                                "id": "samples",
                                "label": "PLAY / REC",
                                "width": 970,
                                "height": 580,
                                "color": "red",
                                "css": "",
                                "on": 1,
                                "off": 0,
                                "value": "",
                                "precision": 2,
                                "address": "/samples",
                                "preArgs": [],
                                "target": [],
                                "matrix": [
                                    4,
                                    4
                                ],
                                "start": 0,
                                "traversing": true,
                                "split": false
                            }
                        ],
                        "type": "tab",
                        "color": "auto",
                        "css": "",
                        "layout": "",
                        "spacing": 0,
                        "value": "",
                        "precision": 0,
                        "address": "/tab_6",
                        "preArgs": [],
                        "target": [],
                        "variables": "@{parent.variables}",
                        "tabs": [],
                        "scroll": true
                    }
                ],
                "type": "tab",
                "color": "auto",
                "css": "",
                "layout": "",
                "spacing": 0,
                "value": "",
                "precision": 0,
                "address": "/tab_1",
                "preArgs": [],
                "target": [],
                "variables": "@{parent.variables}",
                "widgets": [],
                "scroll": true
            }
        ],
        "color": "auto",
        "css": "",
        "value": "",
        "precision": 0,
        "address": "/root",
        "preArgs": [],
        "target": [],
        "variables": {},
        "id": "root",
        "scroll": true,
        "label": false
    }
]